In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 14.5 MB/s  0:00:016m0:00:01

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [ ]:
import numpy as np 
#tensroflow -> tensor
arreglo1D = np.array([5,8,7,5])
print(type(arreglo1D))
print(arreglo1D)
print(arreglo1D.ndim)
print(arreglo1D.shape)
arreglo2D = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(type(arreglo2D))
print(arreglo2D)
print(arreglo2D.ndim)
print(arreglo2D.shape)
arreglo3D = np.array([[[1,2,3], [4,5,6] ], [[7,8,9], [10,11,12]]])
print(arreglo3D)
print(arreglo3D.ndim) #dimensiones
print(arreglo3D.shape) #tamaño del arreglo

#Max, min, mean, sum
print("Arreglos")
maximo = np.max(arreglo1D)
print(maximo)
minimo = np.min(arreglo1D)
print(minimo)
promedio = np.mean(arreglo1D)
print(promedio)
suma = np.sum(arreglo1D)
print(suma)


<class 'numpy.ndarray'>
[5 8 7 5]
1
(4,)
<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
(4, 4)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
Arreglos
8
5
6.25
25


In [23]:
entradas = np.array([0.5,0.67,0.85,0.32])
pesos = np.array([0.14,0.22,0.07,0.10])
bias = 0.09
y_p = np.dot(entradas,pesos)+bias
f_y_p = 1/np.exp(f_y_p)
print(f_y_p)

NameError: name 'f_y_p' is not defined

In [19]:
!pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 10.7 MB/s  0:00:01m0:00:010:01

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [20]:
!pip install matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 10.2 MB/s  0:00:00m0:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 9.7 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 3.6 MB/s  0:00:000m eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 12.5 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [27]:
import pandas as pd
import matplotlib.pyplot as plt
URL = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
df = pd.read_csv(URL) #df significa DataFrame y aqui se manda a llamar el dataset
print(df.head(10)) #muestra los primeros 5 registros
print(type(df))

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa
<class 'pandas.DataFrame'>


In [ ]:
plt.Figure() #
plt.labelx() #lo que se va a mosrar en el eje x
plt.labely() #mostrar en el eje de y
plt.title() #titulo a la grafica a mostrar
plt.show() #decir al compilador que se tiene que mostar algo
plt.scatter() #mostrar los puntos en la grafica

In [28]:
!pip install Scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 14.9 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 22.0 MB/s  0:00:016m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [Scikit-learn] [Scikit-learn]

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
